name: Deploy wp-content to OVH

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "wp-content/themes/**"
      - "wp-content/plugins/**"
      - "wp-content/mu-plugins/**"
      - "wp-content/languages/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy themes via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          security: loose
          server-dir: /www/wp-content/themes/
          local-dir: wp-content/themes/
          dangerous-clean-slate: false

      - name: Deploy plugins via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          security: loose
          server-dir: /www/wp-content/plugins/
          local-dir: wp-content/plugins/
          dangerous-clean-slate: false

      - name: Deploy mu-plugins via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          security: loose
          server-dir: /www/wp-content/mu-plugins/
          local-dir: wp-content/mu-plugins/
          dangerous-clean-slate: false

      - name: Deploy languages via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          security: loose
          server-dir: /www/wp-content/languages/
          local-dir: wp-content/languages/
          dangerous-clean-slate: false
